Repository alifnuryana/sistem-penjaminan-mutu, pull requests merged in 2023-06, with the labels that each got.

#1 fixing ignore file in repository
  .gitignore
  package-lock.json
  yarn.lock
Labels: bug

#3 dark mode feature!
  package.json
  resources/js/Components/Layouts/AppLayout.vue
  resources/js/Components/Layouts/Partials/Header.vue
  resources/js/Components/ThemeSwitcher.vue
  resources/js/Pages/Accreditations/Create.vue
  resources/js/Pages/Accreditations/Index.vue
  resources/js/Pages/Data/Decree/Index.vue
  tailwind.config.js
Labels: bug, enhancement

#4 fix darkmode on autocomplete browser
  resources/css/app.css
  resources/js/Components/InputField.vue
Labels: bug

#5 fix dark mode related on create unit page
  resources/js/Pages/Data/Unit/Create.vue
  resources/js/app.js
Labels: bug

#8 Fix Donwload File
  app/Http/Controllers/DataUnitController.php
  app/Http/Controllers/ShowFileDecreeController.php
  app/Http/Middleware/HandleInertiaRequests.php
  app/Http/Requests/CreateUnitRequest.php
  composer.json
  composer.lock
  config/filepond.php
  database/migrations/2023_06_25_000000_create_fileponds_table.php
  package.json
  resources/js/Components/InputField.vue
  resources/js/Pages/Data/Unit/Create.vue
Labels: bug

#9 replaces browser default file upload with filepond
  app/Actions/Utilities/FilePondUpload.php
  app/Http/Controllers/AccreditationController.php
  app/Http/Controllers/DataUnitController.php
  app/Http/Requests/CreateAccreditationRequest.php
  package.json
  resources/js/Components/FilePondUpload.vue
  resources/js/Composables/useFilesPond.js
  resources/js/Pages/Accreditations/Create.vue
  resources/js/Pages/Data/Unit/Create.vue
Labels: enhancement

#17 WIP Progress
  app/Actions/Notifications/CreateNewNotification.php
  app/Actions/Notifications/PopulateScheduledNotification.php
  app/Actions/Utilities/LoadSamplePdf.php
  app/Console/Commands/AutoAccreditationExpiryDate.php
  app/Console/Kernel.php
  app/Enums/AccreditationStatus.php
  app/Enums/NotificationStatus.php
  app/Events/AccreditationProcessedEvent.php
  app/Events/RemainderAccreditationProcessedEvent.php
  app/Http/Controllers/AccreditationController.php
  app/Http/Controllers/DataIndex.php
  app/Http/Controllers/DataIndexController.php
  app/Http/Controllers/DataUnitController.php
  app/Http/Controllers/MultipleDeleteAccreditationController.php
  app/Http/Controllers/MultipleDeleteUnitController.php
  app/Http/Controllers/SendUnitRemainderController.php
  app/Jobs/ProcessAccreditationJob.php
  app/Jobs/ProcessRemainderAccreditationJob.php
  app/Listeners/NotifyNewAccreditationListener.php
  app/Listeners/NotifyUnitListener.php
  app/Listeners/PopulateNotificationScheduleListener.php
  app/Listeners/UpdateNotificationStatusListener.php
  app/Mail/AccreditationExpiryDate.php
  app/Models/Accreditation.php
  app/Models/Notification.php
  app/Models/Unit.php
  app/Notifications/NewAccreditationNotification.php
  app/Notifications/RemainderUnitNotification.php
  app/Providers/EventServiceProvider.php
  config/app.php
  database/migrations/2023_05_14_121141_create_accreditations_table.php
  database/migrations/2023_06_26_014008_create_notifications_table.php
  database/migrations/2023_06_26_151251_create_jobs_table.php
  database/seeders/AccreditationSeeder.php
  database/seeders/UnitSeeder.php
  resources/assets/images/ok-amico.png
  resources/assets/images/ok-pana.png
  resources/js/Components/Assets/PersonalFileBro.vue
  resources/js/Components/FooterTableNew.vue
  resources/js/Components/UnitInfo.vue
  resources/js/Pages/Accreditations/Create.vue
  resources/js/Pages/Accreditations/Index.vue
  resources/js/Pages/Data/Index.vue
  resources/js/Pages/Data/Unit/Index.vue
  resources/js/Pages/Data/Unit/Show.vue
  resources/views/emails/accreditation-expiry-date.blade.php
  routes/web.php
Labels: bug, enhancement

#19 notification pages complete
  app/Http/Controllers/DataUnitController.php
  app/Http/Controllers/MultipleDeleteNotificationController.php
  app/Http/Controllers/NotificationIndexController.php
  app/Http/Requests/EditUnitRequest.php
  resources/js/Components/FooterTableNew.vue
  resources/js/Components/Layouts/Partials/Sidebar.vue
  resources/js/Composables/useSearchBox.js
  resources/js/Pages/Data/Notification/Index.vue
  resources/js/Pages/Data/Unit/Edit.vue
  resources/js/Pages/Data/Unit/Show.vue
  routes/web.php
Labels: enhancement
